#mvn spring-boot:run -Dspring-boot.run.profiles=microservice
spring:
  config:
    activate:
      on-profile: microservice  
  application:
    name: TEACHER-SERVICE

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
